CREATE TABLE IF NOT EXISTS pastes (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	text TEXT NOT NULL,
	lang TEXT NOT NULL,
	line_count INTEGER NOT NULL,
	addr TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

	CHECK (LENGTH(text) > 0 AND
		LENGTH(lang) > 0 AND
		line_count > 0 AND
		LENGTH(addr) > 0)
);
